# Generated by Django 3.2.4 on 2021-07-01 06:11

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_blog_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content',
            field=froala_editor.fields.FroalaField(null=True),
        ),
    ]
